# -*- coding: utf-8 -*-
"""25011409.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VP_T4OKhzrs7zcyzuLXu2eZjDheHf-j7
"""

import requests


def check_sql_injection(url):
  payload = "' OR'1'='1"
  #sending request
  response = requests.get(url +payload)
  #checking responses
  if "error" in response.text.lower():
    return "potential SQL Injection vulnerability found!"
  return "No SQL Injection Vulnebility detected."
#example usage you can use yours
url = "https://juice-shop.herouapp.com/#/"
result = check_sql_injection(url)
print(result)

